# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

#[[main]]
#  name = "Home"
#  url = "/"
#  weight = 10

[[main]]
  name = "News"
  url = "post"
  weight = 20

[[main]]
  name = "Projects"
 identifier = "P"
  url = "project"
  weight = 30
  
 [[main]]
  name = "Current Projects"
  parent = "P"
  url = "project-curr"
  weight = 10
  
[[main]]
  name = "Past Projects"
  parent = "P"
  url = "project-past"
  weight = 20

[[main]]
  name = "People"
  url = "people"
  weight = 40

[[main]]
  name = "Posters"
  url = "poster"
  weight = 45

[[main]]
  name = "Publications"
  url = "pubcon"
  weight = 50

#[[main]]
#  name = "Contact"
#  url = "contact"
#  weight = 60
